version: "3.8"

services:
  
  node:
    build:
      context: .
      dockerfile: ./DockerFile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dist:/usr/src/app/dist
      - ./views:/usr/src/app/views