FROM node:14
WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./

COPY views/* views/
COPY dist/* dist/
COPY src/* src/


RUN npm install
RUN npx tsc
CMD ["npx", "nodemon", "dist/app.js" ]